name: Conventional Commits

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize
      - edited

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Title
        uses: cresta/action-semantic-release@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          action: "validate"
